# Generated by Django 4.2.1 on 2023-07-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_alter_payment_borrowing_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(max_length=2000),
        ),
    ]
